# Generated by Django 5.0.7 on 2024-09-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GcashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='GCash', max_length=10)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField()),
                ('reference_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerfirstname', models.CharField(max_length=255)),
                ('ownerlastname', models.CharField(max_length=255)),
                ('owneraddress', models.CharField(max_length=255)),
                ('ownercontact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GcashTransactionMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_paid_for', models.IntegerField()),
                ('year_paid_for', models.IntegerField()),
                ('gcash_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='posts.gcashtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bhname', models.CharField(max_length=255, unique=True)),
                ('bhaddress', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=0)),
                ('number_of_tenants', models.IntegerField(default=0)),
                ('bhrooms', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=15)),
                ('capacity', models.IntegerField(default=0)),
                ('boarding_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='posts.boardinghouse')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarderfirstname', models.CharField(max_length=100)),
                ('boardermiddlename', models.CharField(blank=True, max_length=10, null=True)),
                ('boarderlastname', models.CharField(max_length=100)),
                ('boardergender', models.CharField(max_length=50)),
                ('boarderage', models.IntegerField()),
                ('boarderaddress', models.CharField(max_length=200)),
                ('boardercontactnumber', models.CharField(max_length=15)),
                ('boardercourse_profession', models.CharField(max_length=200)),
                ('boarderinstitution', models.CharField(max_length=200)),
                ('monthly_rent', models.FloatField(blank=True, null=True)),
                ('total_monthly_due', models.FloatField(blank=True, null=True)),
                ('initial_payment', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.JSONField(default=dict)),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.room')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardianfirstname', models.CharField(max_length=255)),
                ('guardianmiddlename', models.CharField(max_length=200)),
                ('guardianlastname', models.CharField(max_length=255)),
                ('guardiancontactnumber', models.CharField(max_length=15)),
                ('guardianaddress', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='gcashtransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tenant'),
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='posts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('month_paid_for', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('year_paid_for', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tenant')),
            ],
        ),
    ]
