# Generated by Django 5.0.7 on 2024-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='passcode',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
