# Generated by Django 5.0.7 on 2024-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tenant_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='passcode',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
